"""
Inverse-model solver for differential phase contrast (DPC) stacks using a linear
Rytov forward model and FISTA with a plug-and-play median proximal operator.

The solver maps a 3D refractive-index volume to DPC measurements generated by
half-plane LED patterns, optionally across a focal stack. It reuses the
GPU-aware FFT and linear scattering tools already in the codebase.
"""

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Optional

import numpy as np
import scipy.sparse as sp
from scipy.sparse.linalg import svds

try:
    import cupy as cp
    import cupyx.scipy.sparse as sp_gpu
except ImportError:  # pragma: no cover
    cp = None
    sp_gpu = None

from mcsim.analysis.fft import ft2, ift2
from mcsim.analysis.field_prop import (
    fwd_model_linear,
    get_angular_spectrum_kernel,
    get_v,
)
from mcsim.analysis.optimize import Optimizer, median_prox


if cp:
    array = np.ndarray | cp.ndarray
else:
    array = np.ndarray


def _get_xp(use_gpu: bool):
    return cp if (use_gpu and cp is not None) else np


def _split_dpc_patterns(na_xy: np.ndarray, order: Sequence[str]) -> list[np.ndarray]:
    """
    Split LED NA coordinates into canonical DPC half-planes.
    """
    allowed = ("left", "right", "up", "down")
    if len(order) != 4 or set(order) != set(allowed):
        raise ValueError(f"order must be a permutation of {allowed}, got {order}")

    na_x = na_xy[:, 0]
    na_y = na_xy[:, 1]
    masks = {
        "left": na_x < 0,
        "right": na_x > 0,
        "up": na_y > 0,
        "down": na_y < 0,
    }

    indices: list[np.ndarray] = []
    for name in order:
        idx = np.nonzero(masks[name])[0]
        if idx.size == 0:
            raise ValueError(f"pattern '{name}' has zero LEDs")
        indices.append(idx)
    return indices


def _defocus_kernels(
    ny: int,
    nx: int,
    dxy: float,
    zs: Sequence[float],
    wavelength: float,
    n_medium: float,
    xp,
) -> array:
    """
    Precompute angular spectrum defocus kernels for each focal offset.
    """
    fx = xp.expand_dims(xp.fft.fftfreq(nx, dxy), axis=0)
    fy = xp.expand_dims(xp.fft.fftfreq(ny, dxy), axis=1)
    kernels = [get_angular_spectrum_kernel(fx, fy, z, wavelength, n_medium) for z in zs]
    return xp.stack(kernels, axis=0)


@dataclass
class DPCGeometry:
    """
    Lightweight container for optical and sampling parameters.
    """

    wavelength_um: float
    n_medium: float
    na_obj: float
    camera_pixel_um: float
    magnification: float
    focal_offsets_um: Sequence[float]
    pattern_order: Sequence[str]
    normalize_by_led_count: bool = True

    @property
    def dxy_um(self) -> float:
        return float(self.camera_pixel_um) / float(self.magnification)


class DPCRytovInverse(Optimizer):
    """
    FISTA-compatible optimizer for DPC stacks under a linear Rytov model.
    """

    def __init__(
        self,
        measured: array,
        led_na: np.ndarray,
        *,
        geom: DPCGeometry,
        n_shape: Sequence[int, int, int],
        drs_n: Sequence[float, float, float],
        median_filter_size: Sequence[int, int, int] = (3, 3, 3),
        use_gpu: bool = False,
    ) -> None:
        if measured.ndim == 3:
            measured = measured[None, ...]

        n_planes, n_patterns, ny, nx = measured.shape
        if n_patterns != 4:
            raise ValueError(f"expected 4 DPC patterns, got {n_patterns}")

        xp = _get_xp(use_gpu)
        self.use_gpu = bool(use_gpu)
        self.xp = xp
        self.geom = geom
        self.n_shape = tuple(int(s) for s in n_shape)
        self.drs_n = tuple(float(d) for d in drs_n)
        self.ny = int(ny)
        self.nx = int(nx)
        self.n_planes = int(n_planes)
        self.n_patterns = int(n_patterns)
        self.pattern_order = tuple(geom.pattern_order)
        self.normalize_by_led_count = bool(geom.normalize_by_led_count)
        self.median_filter_size = tuple(int(s) for s in median_filter_size)

        self.data = xp.asarray(measured)
        self.led_na = np.asarray(led_na, dtype=float)
        self.pattern_led_indices = _split_dpc_patterns(self.led_na, self.pattern_order)
        self.pattern_led_indices_gpu = (
            [xp.asarray(idx) for idx in self.pattern_led_indices] if xp is cp else self.pattern_led_indices
        )

        # Sampling/grid
        self.dxy = float(geom.dxy_um)
        self.drs_e = (self.dxy, self.dxy)

        # Forward operator (Rytov linear scattering) for all LEDs at once
        beam_fx = xp.asarray(self.led_na[:, 0] / geom.wavelength_um)
        beam_fy = xp.asarray(self.led_na[:, 1] / geom.wavelength_um)
        beam_fz = xp.sqrt((geom.n_medium / geom.wavelength_um) ** 2 - beam_fx**2 - beam_fy**2)
        self.model = fwd_model_linear(
            beam_fx,
            beam_fy,
            beam_fz,
            geom.n_medium,
            geom.na_obj,
            geom.wavelength_um,
            (self.ny, self.nx),
            self.drs_e,
            self.n_shape,
            self.drs_n,
            mode="rytov",
            interpolate=False,
            use_gpu=self.use_gpu,
        )

        # Defocus transfer functions per plane
        if geom.focal_offsets_um and len(geom.focal_offsets_um) not in (1, n_planes):
            raise ValueError(
                f"focal_offsets_um length ({len(geom.focal_offsets_um)}) must match n_planes ({n_planes}) or be 1"
            )
        self.focal_offsets = [float(z) for z in geom.focal_offsets_um] if geom.focal_offsets_um else [0.0]
        if len(self.focal_offsets) == 1 and n_planes > 1:
            self.focal_offsets = [self.focal_offsets[0]] * n_planes
        if len(self.focal_offsets) != n_planes:
            raise ValueError(f"n_planes={n_planes} but {len(self.focal_offsets)} focal offsets provided")
        self.defocus_kernels = _defocus_kernels(
            self.ny,
            self.nx,
            self.dxy,
            self.focal_offsets,
            geom.wavelength_um,
            geom.n_medium,
            xp,
        )
        self.e0 = xp.ones((self.n_planes, self.ny, self.nx), dtype=complex)

        # Map sample indices -> (plane, pattern)
        self.sample_plane = np.repeat(np.arange(self.n_planes), self.n_patterns)
        self.sample_pattern = np.tile(np.arange(self.n_patterns), self.n_planes)

        super().__init__(self.n_planes * self.n_patterns, prox_parameters={"median_filter_size": self.median_filter_size})

    # ---------------------------
    # helpers
    # ---------------------------
    def _select_indices(self, inds: Optional[Sequence[int]]) -> np.ndarray:
        if inds is None:
            return np.arange(self.n_samples)
        return np.asarray(inds, dtype=int)

    def _predict_fields(self, n_volume: array) -> tuple[array, array]:
        """
        Compute per-pattern irradiance predictions and per-LED defocused fields.
        """
        xp = self.xp
        v = get_v(n_volume, self.geom.n_medium, self.geom.wavelength_um)
        v_vec = xp.asarray(v).ravel()

        es_focus = self.model.dot(v_vec).reshape((self.led_na.shape[0], self.ny, self.nx))
        es_ft = ft2(es_focus, shift=False)
        es_ft = es_ft[:, None, :, :] * self.defocus_kernels[None, :, :, :]
        es_z = ift2(es_ft, shift=False)  # (n_led, n_planes, ny, nx)

        # move plane axis first for easier broadcasting
        es_z = xp.moveaxis(es_z, 1, 0)  # (n_planes, n_led, ny, nx)
        intensity = xp.abs(self.e0[:, None, :, :] + es_z) ** 2

        patterns = []
        idx_list = self.pattern_led_indices_gpu
        for idx in idx_list:
            pat = intensity[:, idx, :, :].sum(axis=1)
            if self.normalize_by_led_count:
                pat = pat / idx.shape[0]
            patterns.append(pat)

        pred = xp.stack(patterns, axis=1)  # (n_planes, 4, ny, nx)
        return pred, es_z

    # ---------------------------
    # Optimizer interface
    # ---------------------------
    def fwd_model(self, x: array, inds: Optional[Sequence[int]] = None) -> array:
        pred, _ = self._predict_fields(x)
        pred_flat = pred.reshape((self.n_samples, self.ny, self.nx))
        sel = self._select_indices(inds)
        return pred_flat[sel]

    def cost(self, x: array, inds: Optional[Sequence[int]] = None) -> array:
        xp = self.xp
        pred, _ = self._predict_fields(x)
        residual = pred - self.data
        residual_flat = residual.reshape((self.n_samples, self.ny, self.nx))
        sel = self._select_indices(inds)
        r = residual_flat[sel]
        return 0.5 * xp.sum(xp.abs(r) ** 2, axis=(-1, -2))

    def gradient(self, x: array, inds: Optional[Sequence[int]] = None) -> array:
        xp = self.xp
        pred, es_z = self._predict_fields(x)
        n_led = self.led_na.shape[0]

        # mask residuals to selected samples
        mask = np.zeros(self.n_samples, dtype=bool)
        sel = self._select_indices(inds)
        mask[sel] = True
        mask_stack = xp.asarray(mask.reshape((self.n_planes, self.n_patterns, 1, 1)))

        residual = (pred - self.data) * mask_stack

        # accumulate per-LED gradient at focus plane
        grad_es0 = xp.zeros((n_led, self.ny, self.nx), dtype=complex)
        idx_list = self.pattern_led_indices_gpu
        for p_idx, led_idx in enumerate(idx_list):
            res_p = residual[:, p_idx, :, :]  # (n_planes, ny, nx)
            scale = 1.0 / led_idx.shape[0] if self.normalize_by_led_count else 1.0
            for l in led_idx.tolist():
                # gradient of irradiance wrt field at each plane
                g_z = res_p * (self.e0 + es_z[:, l, :, :]) * (2.0 * scale)
                # backpropagate defocus for this LED across planes
                g_ft = ft2(g_z, adjoint=True, shift=False)  # (n_planes, ny, nx)
                back_ft = xp.sum(g_ft * xp.conj(self.defocus_kernels), axis=0)
                grad_es0[l] += ift2(back_ft, shift=False)

        # adjoint of linear model
        grad_v_vec = self.model.getH().dot(grad_es0.ravel())
        grad_v = grad_v_vec.reshape(self.n_shape)

        # chain rule dv/dn = -2*(2*pi/lambda)^2 * n
        n_volume = xp.asarray(x)
        factor = -2 * (2 * np.pi / self.geom.wavelength_um) ** 2 * n_volume
        grad_n = grad_v * factor
        # broadcast gradient to requested batch; each selected sample shares the same volume gradient
        return xp.broadcast_to(xp.expand_dims(grad_n, axis=0), (len(sel),) + grad_n.shape)

    def prox(self, x: array, step: float) -> array:
        xp = self.xp
        x_real = median_prox(x.real, self.median_filter_size)
        return xp.asarray(x_real, dtype=x.dtype)

    def guess_step(self, x: Optional[array] = None) -> float:
        """
        Estimate a Lipschitz-consistent step size using the same spectral norm
        logic as `LinearScatt.guess_step`, reusing the sparse linear Rytov model.

        We ignore the mild nonlinearity from intensity formation; this gives a
        conservative step similar to other linear-scattering solvers in mcsim.
        """
        # dominant singular value of the linear model
        try:
            m_for_svd = self.model.get() if sp_gpu and isinstance(self.model, sp_gpu.csr_matrix) else self.model
            u, s, vh = svds(m_for_svd, k=1, which="LM")
            sigma = float(s[0])
        except Exception:
            # fallback if svds not available
            sigma = 1.0

        # exactly match LinearScatt: L ~ sigma^2 / (n_samples * ny * nx)
        lipschitz_estimate = sigma**2 / (self.n_samples * self.ny * self.nx)
        if not np.isfinite(lipschitz_estimate) or lipschitz_estimate <= 0:
            return 1e-3

        return float(1.0 / lipschitz_estimate)
